spring.application.name=inventory
server.port=8000

# Application Name

spring.mongodb.uri=mongodb://localhost:27017/game_inventory

# Logging
logging.level.com.ea.in_game_inventory.inventory=INFO
logging.level.org.springframework.data.mongodb=INFO